on: [push]

jobs:
  deploy_to_now:
    runs-on: ubuntu-latest
    name: Deploy to ZEIT Now
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Deploy
        id: deploy
        uses: ./
      - name: Get total deployment time
        run: echo "Total deployment time ${{ steps.deploy.outputs.deployment-time }}"
